CREATE DATABASE GATEFERIA_NEKOFFEE

USE GATEFERIA_NEKOFFEE

CREATE TABLE CLIENTES(
	NOME_CLIENTE VARCHAR(15) NOT NULL,
	SOBRENOME VARCHAR(40) NOT NULL,
	IDADE INT NOT NULL,
	CPF_CLIENTE VARCHAR(14) NOT NULL,
	TELEFONE VARCHAR(15) NOT NULL,
	EMAIL VARCHAR(254) NOT NULL,
	ID_CLIENTE INT NOT NULL PRIMARY KEY IDENTITY
)

CREATE TABLE INFORMACOES_FINANCEIRAS(
	 AGENCIA_CARTAO VARCHAR(4) NOT NULL,
	 NUMERO_CARTAO VARCHAR(16) NOT NULL,
	 TITULAR_CARTAO VARCHAR(30) NOT NULL,
	 VALIDADE_CARTAO DATE NOT NULL,
	 CODIGO_SEGURANCA INT NOT NULL,
	 ID_FINANCEIRO INT PRIMARY KEY IDENTITY,
	 ID_CLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE)
)

CREATE TABLE GATOS (
	NOME_GATO VARCHAR(15) NOT NULL,
	RACA_GATO VARCHAR(50) NULL,
	IDADE_GATO INT NULL,
	PESO_GATO VARCHAR(2) NOT NULL,
	COR_GATO VARCHAR(50) NOT NULL,
	STATUS_GATO VARCHAR(1) NOT NULL,
	ID_GATO INT NOT NULL PRIMARY KEY IDENTITY,
	ID_DONO INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE)
)

CREATE TABLE ADOCAO (
	ID_ADOCAO INT PRIMARY KEY IDENTITY,
	ID_CLIENTE INT NOT NULL FOREIGN KEY REFERENCES CLIENTES(ID_CLIENTE),
	ID_GATO INT NOT NULL FOREIGN KEY REFERENCES GATOS(ID_GATO),
	DATA_ADOCAO DATE DEFAULT GETDATE() NOT NULL
)